### PR TITLE
10000 patients

### PR DESCRIPTION
**Pull request by aethelwulffe**
Includes a large number of practice information settings, as well as
hundreds of user records.  User records use the legacy security model.

### CODE REVIEW

**Review by tmccormi — APPROVED** [review]

**Comment by tmccormi** [comment]
Though you should update the users to use the corner model at some point

**Comment by tmccormi** [comment]
Current model.. I mean

**Comment by aethelwulffe** [comment]
I am unsure of the requirements for the model.  We have had broken user tables when converting or even just when moving databases before.  I think this may have something to do with Blowfish 'secret'.  I need confirmation of that, and a way around it before I can dependably generate the hashes and all that...or even use the same one for each user.  For all I know, the username might be part of the key.

**Comment by tmccormi** [comment]
Let's ask Kevin Yeh, he wrote it...

**Pull request merged**
